### ISSUE TITLE
[BUG] carousal arrows are getting cropped by navbar on a particular view

### ISSUE THREAD

**Issue by tejas-k3** [GrowthVVork/aov-studios#13]
![image](https://github.com/GrowthVVork/aov-studios/assets/77725958/39d84f0e-9818-42f9-a722-3e24ac56fa81)

**Comment by aswin2108** [comment]
Also position the both buttons to the center it would be more accessible I think!

**Comment by siddhi-gh** [comment]
This is no longer an issue. closing down.
