### ISSUE TITLE
[BUG] Clicking on firm name redirects to 404

### ISSUE THREAD

**Issue by tejas-k3** [GrowthVVork/aov-studios#14]
Clicking on AOV Studios causes 404 
https://github.com/GrowthVVork/aov-studios/assets/77725958/a0163863-4cf8-4fd5-a408-11abbf1ab6ba

**Comment by siddhi-gh** [comment]
Do you want it to redirect it to something or should I remove the hyperlink?

**Comment by tejas-k3** [comment]
Expectation : It should be a static name

**Comment by tejas-k3** [comment]
Let;s remove hyperlink

**Comment by siddhi-gh** [comment]
I'm keeping it since we will need it when we integrate multiple pages (ex-projects).

**Comment by siddhi-gh** [comment]
This is fixed.
