### ISSUE TITLE
[BUG] In mobile view, Nav menu closing icon getting removed

### ISSUE THREAD

**Issue by aswin2108** [GrowthVVork/aov-studios#15]
### Proposed Fix: The 'X' button should remain there itself

https://github.com/GrowthVVork/aov-studios/assets/72661784/f406086b-a3c8-414f-97ef-b67165f077d4

**Comment by aswin2108** [comment]
I would add another small bug related to this .

## Hamburger menu opening and closing automatically

When the window is being resized the menu is opening and closing automatically in a split second

https://github.com/GrowthVVork/aov-studios/assets/72661784/57357b85-34ee-460a-a7eb-896d34a635c5

**Comment by siddhi-gh** [comment]
> I would add another small bug related to this .
> 
> ## Hamburger menu opening and closing automatically
> When the window is being resized the menu is opening and closing automatically in a split second
> 
>  2023-07-17.18-10-47.mp4

That's expected - It's transitioning from desktop screen resolution to tab/mobile screen resolution.
It's not a **Bug** - it's intentional

**Comment by aswin2108** [comment]
It was not there in the portfolio project you made so I thought it would be a bug!

**Comment by siddhi-gh** [comment]
It's there in the Portfolio project too.

**Comment by aswin2108** [comment]
No its not there! Like the layout is changing (it should) but the nav menu is not opening and closing!

**Comment by aswin2108** [comment]
I totally forgot about this! You are right we are not on the same page! So what I am saying is in my video if you watch carefully the nav menu is getting opened, and it closes within a split second automatically when the screen is being resized! It dosent happen in the portfolio! Watch the video from **3sec to 5sec**. In that gap the nav menu opens automatically!

For a sec this is the appearance of the window!
![image](https://github.com/GrowthVVork/aov-studios/assets/72661784/3bc5a483-f042-4c18-803d-0b155418a72f)

**Comment by siddhi-gh** [comment]
This is invalid. closing down.
