### ISSUE TITLE
In page navigation scroll

### ISSUE THREAD

**Issue by aswin2108** [GrowthVVork/aov-studios#18]
In both mobile and desktop view, when the navbar options are clicked the the page is not stopping at the correct location, the title of the section may not be visible, pictures getting cutoff, title getting cutoff. 

Example:
* When "Home" is clicked in both views the image is getting cutoff.
* When "About" is clicked in both views partial title is getting cutoff.
* Services and Portfolio the whole title is getting cutoff

**Comment by siddhi-gh** [comment]
This is invalid. closing down.
